name: Sync master to development

on:
  push:
    branches:
      - master

jobs:
  sync-master-to-development:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Fetch all branches
      run: git fetch --all

    - name: Check for changes between branches
      id: check_diff
      run: |
        git checkout master
        git pull
        git checkout querydsl-7.0
        git pull
        git diff --exit-code master querydsl-7.0
      continue-on-error: true

    - name: Create Pull Request
      if: steps.check_diff.outcome == 'failure'
      run: |
        gh pr create --base querydsl-7.0 --head master -t "Sync master into querydsl-7.0" -b "This PR syncs changes from master into querydsl-7.0"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
